package com.cyb.tms.entity;

// Generated Jun 2, 2016 11:52:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmsEfforts generated by hbm2java
 */
@Entity
@Table(name = "tms_efforts", catalog = "taskmanagement")
public class TmsEfforts implements java.io.Serializable {

	private Long effortId;
	private TmsSprintMst tmsSprintMst;
	private TmsSubtask tmsSubtask;
	private Date loggedDate;
	private int loggedHours;

	public TmsEfforts() {
	}

	public TmsEfforts(TmsSprintMst tmsSprintMst, TmsSubtask tmsSubtask,
			Date loggedDate, int loggedHours) {
		this.tmsSprintMst = tmsSprintMst;
		this.tmsSubtask = tmsSubtask;
		this.loggedDate = loggedDate;
		this.loggedHours = loggedHours;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "EFFORT_ID", unique = true, nullable = false)
	public Long getEffortId() {
		return this.effortId;
	}

	public void setEffortId(Long effortId) {
		this.effortId = effortId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SPRINT_ID", nullable = false)
	public TmsSprintMst getTmsSprintMst() {
		return this.tmsSprintMst;
	}

	public void setTmsSprintMst(TmsSprintMst tmsSprintMst) {
		this.tmsSprintMst = tmsSprintMst;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SUBTASK_ID", nullable = false)
	public TmsSubtask getTmsSubtask() {
		return this.tmsSubtask;
	}

	public void setTmsSubtask(TmsSubtask tmsSubtask) {
		this.tmsSubtask = tmsSubtask;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "LOGGED_DATE", nullable = false, length = 10)
	public Date getLoggedDate() {
		return this.loggedDate;
	}

	public void setLoggedDate(Date loggedDate) {
		this.loggedDate = loggedDate;
	}

	@Column(name = "LOGGED_HOURS", nullable = false)
	public int getLoggedHours() {
		return this.loggedHours;
	}

	public void setLoggedHours(int loggedHours) {
		this.loggedHours = loggedHours;
	}

}
