package com.cyb.tms.entity;
// Generated Jun 1, 2016 11:50:09 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TmsProject generated by hbm2java
 */
@Entity
@Table(name = "tms_project", catalog = "TaskManagement")
public class TmsProject implements java.io.Serializable {

	private Long pid;
	private Date endDate;
	private String name;
	private String projectDesc;
	private Date startDate;
	private Set<TmsModule> tmsModules = new HashSet<TmsModule>(0);
	private Set<TmsUsers> tmsUserses = new HashSet<TmsUsers>(0);
	private Set<TmsSprintMst> tmsSprintMsts = new HashSet<TmsSprintMst>(0);

	public TmsProject() {
	}

	public TmsProject(Date endDate, String name, String projectDesc, Date startDate, Set<TmsModule> tmsModules,
			Set<TmsUsers> tmsUserses, Set<TmsSprintMst> tmsSprintMsts) {
		this.endDate = endDate;
		this.name = name;
		this.projectDesc = projectDesc;
		this.startDate = startDate;
		this.tmsModules = tmsModules;
		this.tmsUserses = tmsUserses;
		this.tmsSprintMsts = tmsSprintMsts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PID", unique = true, nullable = false)
	public Long getPid() {
		return this.pid;
	}

	public void setPid(Long pid) {
		this.pid = pid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "END_DATE", length = 10)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "NAME", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "PROJECT_DESC", length = 100)
	public String getProjectDesc() {
		return this.projectDesc;
	}

	public void setProjectDesc(String projectDesc) {
		this.projectDesc = projectDesc;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "START_DATE", length = 10)
	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsProject")
	public Set<TmsModule> getTmsModules() {
		return this.tmsModules;
	}

	public void setTmsModules(Set<TmsModule> tmsModules) {
		this.tmsModules = tmsModules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsProject")
	public Set<TmsUsers> getTmsUserses() {
		return this.tmsUserses;
	}

	public void setTmsUserses(Set<TmsUsers> tmsUserses) {
		this.tmsUserses = tmsUserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsProject")
	public Set<TmsSprintMst> getTmsSprintMsts() {
		return this.tmsSprintMsts;
	}

	public void setTmsSprintMsts(Set<TmsSprintMst> tmsSprintMsts) {
		this.tmsSprintMsts = tmsSprintMsts;
	}

}
