package com.cyb.tms.entity;

// Generated Jun 2, 2016 11:52:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TmsStatusMst generated by hbm2java
 */
@Entity
@Table(name = "tms_status_mst", catalog = "taskmanagement")
public class TmsStatusMst implements java.io.Serializable {

	private Long statusId;
	private String status;
	private Set<UserStoryStaus> userStoryStauses = new HashSet<UserStoryStaus>(
			0);

	public TmsStatusMst() {
	}

	public TmsStatusMst(String status) {
		this.status = status;
	}

	public TmsStatusMst(String status, Set<UserStoryStaus> userStoryStauses) {
		this.status = status;
		this.userStoryStauses = userStoryStauses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "STATUS_ID", unique = true, nullable = false)
	public Long getStatusId() {
		return this.statusId;
	}

	public void setStatusId(Long statusId) {
		this.statusId = statusId;
	}

	@Column(name = "STATUS", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tmsStatusMst")
	public Set<UserStoryStaus> getUserStoryStauses() {
		return this.userStoryStauses;
	}

	public void setUserStoryStauses(Set<UserStoryStaus> userStoryStauses) {
		this.userStoryStauses = userStoryStauses;
	}

}
